# Generated by Django 5.2.3 on 2025-07-10 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_participants_delete_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, upload_to='event_asset'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='rsvped_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
